[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
# TODO
syn = {version = "2.0.27", features = ["default", "extra-traits", "full"]}
quote = "1.0.32"
proc-macro2 = "1.0.66"